AWSTemplateFormatVersion: '2010-09-09'

Description: Deploys 5 Windows instances with the same configuration, from the specified AMI as managed instances and 3 unmanaged instances
Parameters:
  InstanceProfileName:
    Description: Name of the instance profile to attach
    Type: String
  KeyPairName:
    Description: Keypair for the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription : Must be the name of an existing EC2 Keypair
  InstanceType:
    Description: Amazon EC2 Instance Type
    Type: String
    Default: t2.medium
    AllowedValues: [
      t2.micro,
      t2.medium, 
      t2.large
    ]
  AmiId:
    Description: Ami Id for Windows
    Type: String
  VpcId:
    Description: VPC id for the security group
    Type: String
  RoleName:
    Description: Name of the role to create
    Type: String
  FunctionName:
    Description: Name of the lambda function to create
    Type: String
Resources:
  RDPAccessGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable RDP access via port 3389
      GroupName: RDPAccess
      SecurityGroupIngress:
        CidrIp: 0.0.0.0/0
        FromPort: 3389
        IpProtocol: tcp
        ToPort: 3389
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfileName
      SecurityGroupIds: [!GetAtt RDPAccessGroup.GroupId]
      Tags:
      - Key: Name
        Value: HRAppWindows
      - Key: HRAppEnvironment
        Value: Production
      - Key: Environment
        Value: Production
    DependsOn: RDPAccessGroup
  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfileName
      SecurityGroupIds: [!GetAtt RDPAccessGroup.GroupId]
      Tags:
      - Key: Name
        Value: HRAppWindows
      - Key: HRAppEnvironment
        Value: Production
      - Key: Environment
        Value: Production
    DependsOn: RDPAccessGroup
  Instance3:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfileName
      SecurityGroupIds: [!GetAtt RDPAccessGroup.GroupId]
      Tags:
      - Key: Name
        Value: HRAppWindows
      - Key: HRAppEnvironment
        Value: Production
      - Key: Environment
        Value: Production
    DependsOn: RDPAccessGroup
  Instance4:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfileName
      SecurityGroupIds: [!GetAtt RDPAccessGroup.GroupId]
      Tags:
      - Key: Name
        Value: HRAppWindows
      - Key: HRAppEnvironment
        Value: Production
      - Key: Environment
        Value: Production
    DependsOn: RDPAccessGroup
  Instance5:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref InstanceProfileName
      SecurityGroupIds: [!GetAtt RDPAccessGroup.GroupId]
      Tags:
      - Key: Name
        Value: HRAppWindows
      - Key: HRAppEnvironment
        Value: Production
      - Key: Environment
        Value: Production
    DependsOn: RDPAccessGroup   
  MySNSTopic: 
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "HRApplicationAlerts"
      DisplayName: "HR Application Alerts" 
      Subscription: 
      - Endpoint: 'nanalakshmanan.test@gmail.com'
        Protocol: email
  InstanceProfile:
    Properties:
      Path: "/"
      Roles: [!Ref LambdaRole]
    Type: AWS::IAM::InstanceProfile
    DependsOn: LambdaRole
  LambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
      Path: "/"
      RoleName: !Ref RoleName 
    Type: AWS::IAM::Role
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: "\"Lambda handler for sending email\"\r\nimport boto3\r\n        \r\ndef lambda_handler(event, context):\r\n    \"Sends email message from lambda using SES\"\r\n    if not (('name' in event) and ('to' in event) and ('message' in event)):\r\n        return {\"code\": 1, \"message\": \"Must preovide all values\"}\r\n\r\n    if event['name'] != \"\" and event['to'] != \"\":\r\n        name = event['name']\r\n        toEmail = event['to']\r\n        subject = event['subject']\r\n        message = event['message']\r\n\r\n        fromEmail = \"nanalakshmanan.test@gmail.com\"\r\n        replyTo = fromEmail\r\n        \r\n        subject = \"[\" + name + \"]\" + \":\" + subject \r\n        \r\n        client = boto3.client('ses', region_name='us-east-1')\r\n        response = client.send_email(\r\n\t\t\tSource=fromEmail,\r\n\t\t\tDestination={\r\n\t\t\t\t'ToAddresses': [\r\n\t\t\t\t\ttoEmail,\r\n\t\t\t\t],\r\n\t\t\t},\r\n\t\t\tMessage={\r\n\t\t\t\t'Subject': {\r\n\t\t\t\t\t'Data': subject,\r\n\t\t\t\t\t'Charset': 'utf8'\r\n\t\t\t\t},\r\n\t\t\t\t'Body': {\r\n\t\t\t\t\t'Text': {\r\n\t\t\t\t\t\t'Data': message,\r\n\t\t\t\t\t\t'Charset': 'utf8'\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t)\r\n\t\t\t\r\n        print (response['MessageId'])\r\n        return {'code': 0, 'message': 'success'}"
      Role: !Join ["", ["arn:aws:iam::", !Ref "AWS::AccountId", ":role/", !Ref RoleName ]]
      Timeout: 60
      Handler: index.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      FunctionName: !Ref FunctionName
    DependsOn: InstanceProfile
  PSConfLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: PSConfLogGroup
      RetentionInDays: 90
